---
version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - ./config.ru:/myapp/config.ru:ro
      - ./app.rb:/myapp/app.rb:ro
      - ./migrations:/myapp/migrations:ro
    environment:
      DATABASE_URL: "postgres://postgres@db/recipes"
    depends_on:
      - db
  web:
    image: "nginx:stable-alpine"
    depends_on:
      - api
    volumes:
      - ./static.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/static:ro
    ports:
      - "9292:80"
  db:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_DB: recipes
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  api:
    image: "golang:1.9-alpine"
    volumes:
      - ./src:/go/src:ro
      - ./vendor:/go/vendor:ro
    environment:
      GOPATH: "/go:/go/vendor"
      DATABASE_URL: "postgres://postgres@db/recipes?sslmode=disable"
    depends_on:
      - db
    command: ["go", "run", "src/recipes/cmd/server.go"]
    ports:
      - "8080:8080"
