---
version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - ./config.ru:/myapp/config.ru:ro
      - ./app.rb:/myapp/app.rb:ro
      - ./migrations:/myapp/migrations:ro
      - ./views:/myapp/views:ro
    environment:
      DATABASE_URL: "postgres://postgres@db/recipes"
    depends_on:
      - db
  web:
    image: "nginx:stable-alpine"
    depends_on:
      - app
    volumes:
      - ./static.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/static:ro
    ports:
      - "9292:80"
  db:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_DB: recipes
